### ISSUE TITLE
MMapFileBackedBitArray is returning incorrect bitSize

### ISSUE THREAD

**Issue by asolodin** [sangupta/bloomfilter#1]
MMapFileBackedBitArray.bitSize returns number of bytes in the mmap file instead of the number of elements. This causes the false positives to be much worse than expected.

**Comment by sangupta** [comment]
@asolodin  Per Javadocs for the `bitSize` method:

```
The space used by this {@link BitArray} in number of bytes.
```

`bitSize` does not return the number of elements, but the total space (in bytes) being used by the underlying storage. Hope this helps.
